### ISSUE TITLE
Checklist for next Stable build (v0.1.0.0)

### ISSUE THREAD

**Issue by generalwrex** [HellionCommunity/HellionExtendedServer#44]
Versions will now be
#.0.0.0 - Version  
0.#.0.0 - Stable          
0.0.#.0 - Dev              
0.0.0.#  - Experimental  

Makes this release V0.1.0.0

Let's Discuss!  I'll make a checklist as things progress!

- [ ] Fix the gui chat area to properly show chat ( add copy as well)
- [ ] Add players to player nodes/ offline/ and a list of banned
- [ ] Plugins
- [ ] Plugin Permissions  - 50% Done

**Comment by yungtechboy1** [comment]
- [ ] Permissions
